<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HrisEmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            // Staff / Admin users (also members who can loan)
            [
                'employee_id' => '15-0312',
                'first_name' => 'Jayson',
                'middle_name' => 'P.',
                'last_name' => 'Gamilla',
                'suffix' => null,
                'email' => 'lazada.gamilla@gmail.com',
                'mobile' => '09171234567',
                'employment_type' => 'Permanent',
                'position' => 'System Administrator',
                'department' => 'IT',
                'base_pay' => 45000.00,
                'take_home_pay' => 36000.00,
                'contract_start' => '2015-03-12',
                'contract_end' => null,
                'status' => 'Active',
            ],
            [
                'employee_id' => '15-0313',
                'first_name' => 'Art',
                'middle_name' => null,
                'last_name' => 'Arocena',
                'suffix' => null,
                'email' => 'lazada.gamilla+art@gmail.com',
                'mobile' => '09181234568',
                'employment_type' => 'Permanent',
                'position' => 'Senior Analyst',
                'department' => 'Finance',
                'base_pay' => 35000.00,
                'take_home_pay' => 28000.00,
                'contract_start' => '2015-03-13',
                'contract_end' => null,
                'status' => 'Active',
            ],
            [
                'employee_id' => '15-0314',
                'first_name' => 'Ronnie',
                'middle_name' => null,
                'last_name' => 'Rimando',
                'suffix' => null,
                'email' => 'lazada.gamilla+ronnie@gmail.com',
                'mobile' => '09191234569',
                'employment_type' => 'Permanent',
                'position' => 'Loan Receiver',
                'department' => 'Finance',
                'base_pay' => 32000.00,
                'take_home_pay' => 25600.00,
                'contract_start' => '2015-03-14',
                'contract_end' => null,
                'status' => 'Active',
            ],
            [
                'employee_id' => '15-0315',
                'first_name' => 'Timothy',
                'middle_name' => null,
                'last_name' => 'Rivera',
                'suffix' => null,
                'email' => 'lazada.gamilla+timothy@gmail.com',
                'mobile' => '09201234570',
                'employment_type' => 'Permanent',
                'position' => 'Loan Committee Head',
                'department' => 'Finance',
                'base_pay' => 42000.00,
                'take_home_pay' => 33600.00,
                'contract_start' => '2015-03-15',
                'contract_end' => null,
                'status' => 'Active',
            ],
            [
                'employee_id' => '15-0316',
                'first_name' => 'PMBF',
                'middle_name' => null,
                'last_name' => 'Chair',
                'suffix' => null,
                'email' => 'lazada.gamilla+myline@gmail.com',
                'mobile' => '09211234571',
                'employment_type' => 'Permanent',
                'position' => 'Chairperson',
                'department' => 'Executive',
                'base_pay' => 60000.00,
                'take_home_pay' => 48000.00,
                'contract_start' => '2015-03-16',
                'contract_end' => null,
                'status' => 'Active',
            ],

            // Additional Permanent employees
            [
                'employee_id' => '17-0418',
                'first_name' => 'Ana',
                'middle_name' => 'Lim',
                'last_name' => 'Santos',
                'suffix' => null,
                'email' => 'ana.santos@philrice.gov.ph',
                'mobile' => '09221234572',
                'employment_type' => 'Permanent',
                'position' => 'Accounting Supervisor',
                'department' => 'Accounting',
                'base_pay' => 38000.00,
                'take_home_pay' => 30400.00,
                'contract_start' => '2017-04-18',
                'contract_end' => null,
                'status' => 'Active',
            ],
            [
                'employee_id' => '19-0205',
                'first_name' => 'Maria',
                'middle_name' => 'Reyes',
                'last_name' => 'Garcia',
                'suffix' => null,
                'email' => 'maria.garcia@philrice.gov.ph',
                'mobile' => '09231234573',
                'employment_type' => 'Permanent',
                'position' => 'HR Officer',
                'department' => 'Human Resources',
                'base_pay' => 30000.00,
                'take_home_pay' => 24000.00,
                'contract_start' => '2019-02-05',
                'contract_end' => null,
                'status' => 'Active',
            ],
            [
                'employee_id' => '18-0610',
                'first_name' => 'Jose',
                'middle_name' => 'Mendoza',
                'last_name' => 'Rizal',
                'suffix' => 'Jr.',
                'email' => 'jose.rizal@philrice.gov.ph',
                'mobile' => '09241234574',
                'employment_type' => 'Permanent',
                'position' => 'IT Manager',
                'department' => 'Information Technology',
                'base_pay' => 45000.00,
                'take_home_pay' => 36000.00,
                'contract_start' => '2018-06-10',
                'contract_end' => null,
                'status' => 'Active',
            ],

            // Test registration (not pre-registered in PMBF)
            [
                'employee_id' => '20-0501',
                'first_name' => 'Luis',
                'middle_name' => null,
                'last_name' => 'Tamani',
                'suffix' => null,
                'email' => 'lazada.gamilla+luis@gmail.com',
                'mobile' => '09301234580',
                'employment_type' => 'Permanent',
                'position' => 'Research Associate',
                'department' => 'Research',
                'base_pay' => 30000.00,
                'take_home_pay' => 24000.00,
                'contract_start' => '2020-05-01',
                'contract_end' => null,
                'status' => 'Active',
            ],

            // SC (Service Contract) employees
            [
                'employee_id' => '25-0601',
                'first_name' => 'Carlo',
                'middle_name' => 'Torres',
                'last_name' => 'Bautista',
                'suffix' => null,
                'email' => 'lazada.gamilla+carlo@gmail.com',
                'mobile' => '09251234575',
                'employment_type' => 'SC',
                'position' => 'Project Assistant',
                'department' => 'Operations',
                'base_pay' => 18000.00,
                'take_home_pay' => 15000.00,
                'contract_start' => '2026-01-01',
                'contract_end' => '2026-12-31',
                'status' => 'Active',
            ],
            [
                'employee_id' => '25-0715',
                'first_name' => 'Rica',
                'middle_name' => 'Fernandez',
                'last_name' => 'Villanueva',
                'suffix' => null,
                'email' => 'lazada.gamilla+rica@gmail.com',
                'mobile' => '09261234576',
                'employment_type' => 'SC',
                'position' => 'Administrative Aide',
                'department' => 'Admin',
                'base_pay' => 15000.00,
                'take_home_pay' => 12500.00,
                'contract_start' => '2026-01-01',
                'contract_end' => '2026-09-30',
                'status' => 'Active',
            ],
            [
                'employee_id' => '26-0121',
                'first_name' => 'Mark',
                'middle_name' => 'Aquino',
                'last_name' => 'Gonzales',
                'suffix' => null,
                'email' => 'lazada.gamilla+mark@gmail.com',
                'mobile' => '09271234577',
                'employment_type' => 'SC',
                'position' => 'Field Worker',
                'department' => 'Operations',
                'base_pay' => 12000.00,
                'take_home_pay' => 4500.00,
                'contract_start' => '2026-01-21',
                'contract_end' => '2026-12-31',
                'status' => 'Active',
            ],

            // Non-Members
            [
                'employee_id' => '25-0901',
                'first_name' => 'Luis',
                'middle_name' => 'Ramos',
                'last_name' => 'Tan',
                'suffix' => null,
                'email' => 'lazada.gamilla+luistan@gmail.com',
                'mobile' => '09281234578',
                'employment_type' => 'Non-Member',
                'position' => 'Consultant',
                'department' => 'External',
                'base_pay' => 25000.00,
                'take_home_pay' => 22000.00,
                'contract_start' => '2025-09-01',
                'contract_end' => '2026-06-30',
                'status' => 'Active',
            ],
            [
                'employee_id' => '25-0932',
                'first_name' => 'Grace',
                'middle_name' => 'Pascual',
                'last_name' => 'Lim',
                'suffix' => null,
                'email' => 'lazada.gamilla+grace@gmail.com',
                'mobile' => '09291234579',
                'employment_type' => 'Non-Member',
                'position' => 'Part-time Staff',
                'department' => 'Admin',
                'base_pay' => 10000.00,
                'take_home_pay' => 9000.00,
                'contract_start' => '2025-09-15',
                'contract_end' => '2026-08-31',
                'status' => 'Active',
            ],
        ];

        foreach ($employees as $employee) {
            $employee['created_at'] = now();
            $employee['updated_at'] = now();
            DB::connection('hris')->table('employees')->updateOrInsert(
                ['employee_id' => $employee['employee_id']],
                $employee
            );
        }
    }
}
